[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.render]
build-command = "pip install -r requirements.txt && python manage.py collectstatic --no-input"
start-command = "gunicorn malware_detector.wsgi:application"
